/* Real astronomical facts (IAU / NASA planetary fact sheet figures).
   Orbit radius / size / speed below are compressed for a legible desktop
   scene — a true-to-scale solar system is either invisible (Pluto-scale
   distances) or unusable (real orbital periods span 88 days to 165 years).
   Every info-panel fact shown to the user is real; only the animation's
   spatial/temporal scale is artistic, same as any physical orrery model. */

export const PLANETS = [
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'Terrestrial',
    diameterKm: '4,879 km',
    distanceFromSun: '57.9M km',
    moons: '0',
    orbitalPeriod: '88 days',
    color: '#b5a397',
    orbitRadius: 6.2,
    size: 0.32,
    orbitSpeed: 0.24,
    rotationSpeed: 0.02,
    tilt: 0.001,
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'Terrestrial',
    diameterKm: '12,104 km',
    distanceFromSun: '108.2M km',
    moons: '0',
    orbitalPeriod: '225 days',
    color: '#e8cda0',
    orbitRadius: 8.4,
    size: 0.55,
    orbitSpeed: 0.176,
    rotationSpeed: -0.008,
    tilt: 3.1,
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'Terrestrial',
    diameterKm: '12,742 km',
    distanceFromSun: '149.6M km',
    moons: '1',
    orbitalPeriod: '365.25 days',
    color: '#4d8fdc',
    orbitRadius: 11,
    size: 0.58,
    orbitSpeed: 0.14,
    rotationSpeed: 0.5,
    tilt: 0.41,
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'Terrestrial',
    diameterKm: '6,779 km',
    distanceFromSun: '227.9M km',
    moons: '2',
    orbitalPeriod: '687 days',
    color: '#c1553a',
    orbitRadius: 14,
    size: 0.4,
    orbitSpeed: 0.09,
    rotationSpeed: 0.48,
    tilt: 0.44,
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'Gas Giant',
    diameterKm: '139,820 km',
    distanceFromSun: '778.5M km',
    moons: '95+',
    orbitalPeriod: '11.9 years',
    color: '#d8ae7e',
    orbitRadius: 19,
    size: 1.7,
    orbitSpeed: 0.042,
    rotationSpeed: 1.1,
    tilt: 0.05,
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'Gas Giant',
    diameterKm: '116,460 km',
    distanceFromSun: '1.43B km',
    moons: '146+',
    orbitalPeriod: '29.5 years',
    color: '#e3cd9a',
    orbitRadius: 24.5,
    size: 1.45,
    orbitSpeed: 0.031,
    rotationSpeed: 1.0,
    tilt: 0.47,
    hasRings: true,
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'Ice Giant',
    diameterKm: '50,724 km',
    distanceFromSun: '2.87B km',
    moons: '28',
    orbitalPeriod: '84 years',
    color: '#9fd8dd',
    orbitRadius: 29,
    size: 0.95,
    orbitSpeed: 0.021,
    rotationSpeed: 0.7,
    tilt: 1.71,
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'Ice Giant',
    diameterKm: '49,244 km',
    distanceFromSun: '4.50B km',
    moons: '16',
    orbitalPeriod: '165 years',
    color: '#5170d4',
    orbitRadius: 33,
    size: 0.92,
    orbitSpeed: 0.017,
    rotationSpeed: 0.68,
    tilt: 0.49,
  },
];

export const SUN = {
  name: 'Sun',
  type: 'G-type Main-Sequence Star',
  diameterKm: '1,392,700 km',
  surfaceTemp: '~5,500°C',
  age: '~4.6 billion years',
};

export const MOON = {
  name: 'Moon',
  type: "Earth's natural satellite",
  diameterKm: '3,474 km',
  distanceFromEarth: '384,400 km',
};
