import { lazy } from 'react';
import {
  IconPerson, IconCareer, IconRocket, IconPrompt, IconConstellation, IconPlane,
  IconPulse, IconTopology, IconCandles, IconFolder, IconNote, IconTrash, IconGear, IconChat,
  IconWrench, IconCalendar,
} from '../os/icons';
import { GithubIcon } from '../components/SocialIcons';

export const APPS = {
  about: {
    id: 'about',
    tint: ['#6366f1', '#8b5cf6'],
    title: 'About Me',
    icon: IconPerson,
    component: lazy(() => import('../components/About')),
    defaultSize: { width: 760, height: 620 },
    defaultPosition: { x: 120, y: 90 },
    minSize: { width: 420, height: 360 },
  },
  experience: {
    id: 'experience',
    tint: ['#f59e0b', '#f97316'],
    title: 'Experience',
    icon: IconCareer,
    component: lazy(() => import('../components/Experience')),
    defaultSize: { width: 720, height: 560 },
    defaultPosition: { x: 180, y: 120 },
    minSize: { width: 420, height: 340 },
  },
  projects: {
    id: 'projects',
    tint: ['#06b6d4', '#3b82f6'],
    title: 'Projects',
    icon: IconRocket,
    component: lazy(() => import('../components/Projects')),
    defaultSize: { width: 900, height: 640 },
    defaultPosition: { x: 240, y: 70 },
    minSize: { width: 480, height: 400 },
  },
  terminal: {
    id: 'terminal',
    tint: ['#1e293b', '#0f172a'],
    iconColor: '#4ade80',
    title: 'Terminal',
    icon: IconPrompt,
    component: lazy(() => import('../components/Terminal')),
    defaultSize: { width: 760, height: 480 },
    defaultPosition: { x: 300, y: 160 },
    minSize: { width: 420, height: 320 },
  },
  files: {
    id: 'files',
    tint: ['#38bdf8', '#0284c7'],
    title: 'Files',
    icon: IconFolder,
    component: lazy(() => import('./FilesApp')),
    defaultSize: { width: 680, height: 520 },
    defaultPosition: { x: 210, y: 110 },
    minSize: { width: 440, height: 360 },
  },
  notes: {
    id: 'notes',
    tint: ['#fbbf24', '#d97706'],
    title: 'Notes',
    icon: IconNote,
    component: lazy(() => import('./NotesApp')),
    defaultSize: { width: 720, height: 520 },
    defaultPosition: { x: 250, y: 130 },
    minSize: { width: 460, height: 360 },
  },
  skills: {
    id: 'skills',
    tint: ['#a855f7', '#ec4899'],
    title: 'Skills',
    icon: IconConstellation,
    component: lazy(() => import('../components/SkillsConstellation')),
    defaultSize: { width: 820, height: 600 },
    defaultPosition: { x: 160, y: 80 },
    minSize: { width: 480, height: 400 },
  },
  contact: {
    id: 'contact',
    tint: ['#3b82f6', '#0ea5e9'],
    title: 'Contact',
    icon: IconPlane,
    component: lazy(() => import('../components/Contact')),
    defaultSize: { width: 800, height: 620 },
    defaultPosition: { x: 220, y: 100 },
    minSize: { width: 460, height: 420 },
  },
  monitor: {
    id: 'monitor',
    tint: ['#10b981', '#059669'],
    title: 'System Monitor',
    icon: IconPulse,
    component: lazy(() => import('./SystemMonitor')),
    defaultSize: { width: 680, height: 560 },
    defaultPosition: { x: 260, y: 130 },
    minSize: { width: 420, height: 380 },
  },
  github: {
    id: 'github',
    tint: ['#3d434b', '#24292e'],
    title: 'GitHub',
    icon: GithubIcon,
    component: lazy(() => import('./GitHubApp')),
    defaultSize: { width: 700, height: 580 },
    defaultPosition: { x: 200, y: 90 },
    minSize: { width: 420, height: 400 },
  },
  architecture: {
    id: 'architecture',
    tint: ['#8b5cf6', '#6366f1'],
    title: 'Architecture Lab',
    icon: IconTopology,
    component: lazy(() => import('./ArchitectureLab')),
    defaultSize: { width: 820, height: 520 },
    defaultPosition: { x: 160, y: 100 },
    minSize: { width: 520, height: 400 },
  },
  chat: {
    id: 'chat',
    tint: ['#6366f1', '#818cf8'],
    title: 'AK Chat',
    icon: IconChat,
    component: lazy(() => import('./ChatApp')),
    defaultSize: { width: 640, height: 560 },
    defaultPosition: { x: 230, y: 90 },
    minSize: { width: 400, height: 420 },
  },
  trade: {
    id: 'trade',
    tint: ['#0d9488', '#115e59'],
    title: 'AK Trade',
    icon: IconCandles,
    component: lazy(() => import('../components/Trading')),
    defaultSize: { width: 920, height: 660 },
    defaultPosition: { x: 190, y: 60 },
    minSize: { width: 520, height: 440 },
  },
  calendar: {
    id: 'calendar',
    tint: ['#ef4444', '#dc2626'],
    title: 'Calendar',
    icon: IconCalendar,
    component: lazy(() => import('./CalendarApp')),
    defaultSize: { width: 420, height: 620 },
    defaultPosition: { x: 280, y: 80 },
    minSize: { width: 340, height: 460 },
  },
  devtools: {
    id: 'devtools',
    tint: ['#f97316', '#ea580c'],
    title: 'Dev Toolbox',
    icon: IconWrench,
    component: lazy(() => import('./DevToolboxApp')),
    defaultSize: { width: 620, height: 560 },
    defaultPosition: { x: 260, y: 100 },
    minSize: { width: 460, height: 420 },
  },
  trash: {
    id: 'trash',
    tint: ['#6b7280', '#4b5563'],
    title: 'Trash',
    icon: IconTrash,
    component: lazy(() => import('./TrashApp')),
    defaultSize: { width: 560, height: 460 },
    defaultPosition: { x: 320, y: 150 },
    minSize: { width: 400, height: 320 },
  },
  settings: {
    id: 'settings',
    tint: ['#64748b', '#475569'],
    title: 'Settings',
    icon: IconGear,
    component: lazy(() => import('./Settings')),
    defaultSize: { width: 680, height: 560 },
    defaultPosition: { x: 340, y: 110 },
    minSize: { width: 420, height: 420 },
  },
};

export const APP_LIST = Object.values(APPS);
