import { lazy } from 'react';
import { User, Briefcase, FolderKanban, TerminalSquare, Sparkles, Mail, Activity, Settings as SettingsIcon, Network } from 'lucide-react';
import { GithubIcon } from '../components/SocialIcons';

export const APPS = {
  about: {
    id: 'about',
    title: 'About Me',
    icon: User,
    component: lazy(() => import('../components/About')),
    defaultSize: { width: 760, height: 620 },
    defaultPosition: { x: 120, y: 90 },
    minSize: { width: 420, height: 360 },
  },
  experience: {
    id: 'experience',
    title: 'Experience',
    icon: Briefcase,
    component: lazy(() => import('../components/Experience')),
    defaultSize: { width: 720, height: 560 },
    defaultPosition: { x: 180, y: 120 },
    minSize: { width: 420, height: 340 },
  },
  projects: {
    id: 'projects',
    title: 'Projects',
    icon: FolderKanban,
    component: lazy(() => import('../components/Projects')),
    defaultSize: { width: 900, height: 640 },
    defaultPosition: { x: 240, y: 70 },
    minSize: { width: 480, height: 400 },
  },
  terminal: {
    id: 'terminal',
    title: 'Terminal',
    icon: TerminalSquare,
    component: lazy(() => import('../components/Terminal')),
    defaultSize: { width: 760, height: 480 },
    defaultPosition: { x: 300, y: 160 },
    minSize: { width: 420, height: 320 },
  },
  skills: {
    id: 'skills',
    title: 'Skills',
    icon: Sparkles,
    component: lazy(() => import('../components/SkillsConstellation')),
    defaultSize: { width: 820, height: 600 },
    defaultPosition: { x: 160, y: 80 },
    minSize: { width: 480, height: 400 },
  },
  contact: {
    id: 'contact',
    title: 'Contact',
    icon: Mail,
    component: lazy(() => import('../components/Contact')),
    defaultSize: { width: 800, height: 620 },
    defaultPosition: { x: 220, y: 100 },
    minSize: { width: 460, height: 420 },
  },
  monitor: {
    id: 'monitor',
    title: 'System Monitor',
    icon: Activity,
    component: lazy(() => import('./SystemMonitor')),
    defaultSize: { width: 680, height: 560 },
    defaultPosition: { x: 260, y: 130 },
    minSize: { width: 420, height: 380 },
  },
  github: {
    id: 'github',
    title: 'GitHub',
    icon: GithubIcon,
    component: lazy(() => import('./GitHubApp')),
    defaultSize: { width: 700, height: 580 },
    defaultPosition: { x: 200, y: 90 },
    minSize: { width: 420, height: 400 },
  },
  architecture: {
    id: 'architecture',
    title: 'Architecture Lab',
    icon: Network,
    component: lazy(() => import('./ArchitectureLab')),
    defaultSize: { width: 820, height: 520 },
    defaultPosition: { x: 160, y: 100 },
    minSize: { width: 520, height: 400 },
  },
  settings: {
    id: 'settings',
    title: 'Settings',
    icon: SettingsIcon,
    component: lazy(() => import('./Settings')),
    defaultSize: { width: 560, height: 560 },
    defaultPosition: { x: 340, y: 110 },
    minSize: { width: 400, height: 420 },
  },
};

export const APP_LIST = Object.values(APPS);
