#!/usr/bin/env node
/* Snapshot the public GitHub profile into a committed file.
 *
 *   npm run snapshot:github
 *
 * The app used to call api.github.com from the browser on every visit.
 * Unauthenticated that is 60 requests per hour *per IP*, which is fine
 * while one person is looking and rate-limits the moment anyone shares
 * the link — and it put a network round-trip in the render path of a
 * scene. A snapshot is committed, instant, and works offline; the live
 * call survives only as an optional refresh after paint.
 *
 * Failure never clobbers. If GitHub is unreachable or rate-limited the
 * existing snapshot is left exactly as it is, because stale real data
 * beats an empty file that would silently delete repositories from the
 * trace.
 */
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const USERNAME = process.env.GITHUB_USERNAME || 'akashkasture';
const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/github.js');

// A token is optional. Without one this still works; with one the rate
// limit goes from 60/hr to 5000/hr, which matters in CI.
const headers = {
  Accept: 'application/vnd.github+json',
  'User-Agent': `${USERNAME}-portfolio-snapshot`,
  ...(process.env.GITHUB_TOKEN ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {}),
};

async function get(url) {
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
  return res.json();
}

function bail(message) {
  console.error(`\n  snapshot:github — ${message}`);
  if (existsSync(OUT)) {
    const age = readFileSync(OUT, 'utf8').match(/fetchedAt: "([^"]+)"/)?.[1] ?? 'an earlier run';
    console.error(`  keeping the existing snapshot from ${age}\n`);
    process.exit(0); // not a build failure: the committed data is still good
  }
  console.error('  and there is no existing snapshot to fall back to\n');
  process.exit(1);
}

try {
  const [profile, repos] = await Promise.all([
    get(`https://api.github.com/users/${USERNAME}`),
    get(`https://api.github.com/users/${USERNAME}/repos?per_page=100&sort=updated`),
  ]);

  /* Only the fields the site actually renders. Storing the raw payload
     would commit ~40 kB of URLs and permission flags per repo that
     nothing reads and that churn the diff on every snapshot. */
  const snapshot = {
    fetchedAt: new Date().toISOString(),
    username: USERNAME,
    profile: {
      name: profile.name,
      login: profile.login,
      bio: profile.bio,
      avatarUrl: profile.avatar_url,
      htmlUrl: profile.html_url,
      publicRepos: profile.public_repos,
      followers: profile.followers,
      following: profile.following,
      createdAt: profile.created_at,
    },
    repos: repos
      // Forks are someone else's work. They belong on a profile, not in
      // a trace of what this person built.
      .filter((r) => !r.fork && !r.archived)
      .map((r) => ({
        name: r.name,
        description: r.description,
        htmlUrl: r.html_url,
        language: r.language,
        topics: r.topics || [],
        stars: r.stargazers_count,
        forks: r.forks_count,
        createdAt: r.created_at,
        pushedAt: r.pushed_at,
      }))
      .sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt)),
  };

  /* Written as a JS module rather than JSON, to match portfolio.js and
     posts.js — and because a bare JSON import needs an import attribute
     in Node while Vite resolves it without one, so the same file would
     load in the bundler and fail in any plain-node script that reads the
     data layer. */
  const body = `/* Generated by \`npm run snapshot:github\` — do not edit by hand.
   Committed on purpose: the site reads this instead of calling
   api.github.com on every visit. Re-run the script to refresh. */

export const github = ${JSON.stringify(snapshot, null, 2).replace(/"([^"\\]*)":/g, '$1:')};

export default github;
`;
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, body);
  console.log(
    `\n  snapshot:github — ${snapshot.repos.length} repositories, ` +
      `${snapshot.profile.followers} followers → src/data/github.js\n`
  );
} catch (err) {
  bail(err.message);
}
